service: words

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MONGO_URI: ${file(./config.yml):MONGO_URI}
    JWKS_URI: ${file(./config.yml):JWKS_URI}
    AUDIENCE: ${file(./config.yml):AUDIENCE}
    TOKEN_ISSUER: ${file(./config.yml):TOKEN_ISSUER}

functions:

  authenticate:
    handler: handler.authenticate

  getWords:
    handler: handler.getWords
    events:
      - http:
          path: words
          method: get
          cors: true

  getWord:
    handler: handler.getWord
    events:
      - http:
          path: words/{word_id}
          method: get
          cors: true

  getUser:
    handler: handler.getUser
    events:
      - http:
          path: users/{user_id}
          method: get
          cors: true
          authorizer: authenticate
